Improves "Duplicate Queue Names" section
laravel/vapor-docs pull request #165
Opened 2023-02-20 15:45 UTC by nunomaduro

This pull request improves "Duplicate Queue Names" section, by mentioning `SQS_SUFFIX` environment variable as a easy way to avoid collisions.

2023-02-20 16:00 UTC, joedixon commented on 1.0/resources/queues.md
> +When using custom queue names, it is important to ensure the names are unique between projects and environments. One easy way to accomplish this is by using the `SQS_SUFFIX` environment variable in e
```suggestion
When using custom queue names, it is important to ensure the names are unique between projects and environments. One easy way to accomplish this is by using the `SQS_SUFFIX` environment variable in each environment. This guarantees that custom queues have a unique name in SQS.
```

2023-02-20 16:00 UTC, joedixon requested changes
TIL 🔥

Just one suggestion

2023-02-21 11:57 UTC, taylorotwell commented
@nunomaduro can we show an example of actually doing it?

2023-02-21 17:17 UTC, joedixon commented on 1.0/resources/queues.md
> +When using the same custom queue names, you will need to ensure that the names are unique between projects and environments. One way to achieve this is to use the `SQS_SUFFIX` environment variable in
```suggestion
When using custom queue names, it is important to ensure the names are unique between projects and environments. One way to achieve this is to use the `SQS_SUFFIX` environment variable in each environment. For instance, you can add suffix values such as `-staging` and `-production` to the `SQS_SUFFIX` environment variable, and append it to the queue names specified in your vapor.yml file. A sample configuration is shown below:
```

2023-02-21 18:54 UTC, merged